{% set name = "yandex-query-client" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yandex_query_client-{{ version }}.tar.gz
  sha256: 742f1d08da817353846ec92debda68f180be837eb624f9c833a2158f4b7b6c3c
  patches:
    - 0001-remove-typing.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pandas >=1.2.5
    - python-dateutil >=2.8.2
    - requests >=2.31.0
    - typing >=3.7.4.3
    - urllib3 >=1.26.5

test:
  imports:
    - yandex_query_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yandex-cloud/yandex-query-client
  summary: The Yandex Query official HTTP client
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/yandex-cloud/yandex-query-client
  doc_url: https://github.com/yandex-cloud/yandex-query-client/blob/main/README.md


extra:
  recipe-maintainers:
    - xylar
